### ISSUE TITLE
FATAL Error of TimeOut Exception

### ISSUE THREAD

**Issue by ateotia** [Cdiscount/API-MarketPlace-SDK-PHP#16]
PHP Fatal error:  Uncaught exception 'Zend\\Http\\Client\\Adapter\\Exception\\TimeoutException' with message 'Read timed out' in /var/www/html/cdiscount/vendor/zendframework/zend-http/src/Client/Adapter/Curl.php:453\nStack trace:\n#0 /var/www/html/cdiscount/vendor/zendframework/zend-http/src/Client.php(1428): Zend\\Http\\Client\\Adapter\\Curl->write('GET', Object(Zend\\Uri\\Http), '1.1', Array, '')\n#1 /var/www/html/cdiscount/vendor/zendframework/zend-http/src/Client.php(923): Zend\\Http\\Client->doRequest(Object(Zend\\Uri\\Http), 'GET', true, Array, '')\n#2 /var/www/html/cdiscount/sdk/src/core/HttpTools/CDSApiRequest.php(91): Zend\\Http\\Client->send(Object(Zend\\Http\\Request))\n#3 /var/www/html/cdiscount/sdk/src/core/Auth/Token.php(87): Sdk\\HttpTools\\CDSApiRequest->execute()\n#4 /var/www/html/cdiscount/sdk/src/core/Auth/Token.php(115): Sdk\\Auth\\Token->_generateNewToken()\n#5 /var/www/html/cdiscount/sdk/src/public/ApiClient/CDSApiClient.php(144): Sdk\\Auth\\Token->getToken()\n#6 /var/www/html/cdiscount/samples/Seller/GetSellerInformation.php(15): Sdk\\Ap in /var/www/html/cdiscount/vendor/zendframework/zend-http/src/Client/Adapter/Curl.php on line 453

**Comment by mtkumar82** [comment]
I am getting the same issue, Anybody there to help us in this metter please?

**Comment by p3t3rB4nni3r** [comment]
Same issue here.

**Comment by p3t3rB4nni3r** [comment]
Just change your api.urltoken and api.url. Watch out for preprod 'clsing days' (https://dev.cdiscount.com/marketplace/)

**Comment by mtkumar82** [comment]
Where we need to change this url? I am using Cdiscount php SDK. Please help

**Comment by ChrisToxz** [comment]
For me it is working on 'prod' mode without changing urltoken and api.url.
Peter means with 'closing days' that somedays 'premode' will be unavailable.
![image](https://user-images.githubusercontent.com/28065282/35293376-c7c25bb2-0073-11e8-93cc-e875594e856c.png)
Today (23-01) their 'prepod' is disable and I got exact the same error.

**Comment by Klemart3D** [comment]
Same issue here today, with a preprod seems not in closing days :

![](https://imgur.com/pRUb7R2.jpg)

![](https://imgur.com/nqE9Is2.jpg)

**Comment by yoandm** [comment]
Same for me today.
